[package]
name = "wifi-cli-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
dns-lookup = "2.0.2"
rustyline = "11.0.0"
surge-ping = "0.8.0"
tokio = { version = "1.28.2", features = ["full"] }
unicode-width = "0.1.10"
wifi-rs = { git = "https://github.com/tnkemdilim/wifi-rs.git" }
